name: pieg
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=11.1
  - pip:
    - termcolor==1.1.0
    - dm-control==0.0.425341097
    - tb-nightly==2.9.0a20220326
    - torch==1.9.0+cu111
    - torchvision==0.10.0+cu111
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - mujoco_py==2.0.2.13
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - wandb==0.11.1
