name: dmcgb
channels:
  - defaults
dependencies:
  - python=3.7.6
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - numpy==1.19.5
    - pillow==6.2.0
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - tqdm
    - einops
    - kornia
